export const COUNTRIES = [
  { code: "TR", name: "Türkiye" },
  { code: "DE", name: "Almanya" },
  { code: "US", name: "ABD" },
  { code: "GB", name: "Birleşik Krallık" },
  { code: "FR", name: "Fransa" },
  { code: "IT", name: "İtalya" },
  { code: "ES", name: "İspanya" },
  { code: "NL", name: "Hollanda" },
  { code: "BE", name: "Belçika" },
  { code: "PL", name: "Polonya" },
  { code: "SE", name: "İsveç" },
  { code: "NO", name: "Norveç" },
  { code: "DK", name: "Danimarka" },
  { code: "FI", name: "Finlandiya" },
  { code: "CH", name: "İsviçre" },
  { code: "AT", name: "Avusturya" },
  { code: "PT", name: "Portekiz" },
  { code: "GR", name: "Yunanistan" },
  { code: "CZ", name: "Çek Cumhuriyeti" },
  { code: "HU", name: "Macaristan" },
  { code: "RO", name: "Romanya" },
  { code: "BG", name: "Bulgaristan" },
  { code: "HR", name: "Hırvatistan" },
  { code: "SK", name: "Slovakya" },
  { code: "UA", name: "Ukrayna" },
  { code: "RU", name: "Rusya" },
  { code: "CN", name: "Çin" },
  { code: "JP", name: "Japonya" },
  { code: "KR", name: "Güney Kore" },
  { code: "IN", name: "Hindistan" },
  { code: "SG", name: "Singapur" },
  { code: "AE", name: "Birleşik Arap Emirlikleri" },
  { code: "SA", name: "Suudi Arabistan" },
  { code: "IL", name: "İsrail" },
  { code: "EG", name: "Mısır" },
  { code: "MA", name: "Fas" },
  { code: "ZA", name: "Güney Afrika" },
  { code: "NG", name: "Nijerya" },
  { code: "KE", name: "Kenya" },
  { code: "CA", name: "Kanada" },
  { code: "MX", name: "Meksika" },
  { code: "BR", name: "Brezilya" },
  { code: "AR", name: "Arjantin" },
  { code: "CL", name: "Şili" },
  { code: "CO", name: "Kolombiya" },
  { code: "AU", name: "Avustralya" },
  { code: "NZ", name: "Yeni Zelanda" },
  { code: "AZ", name: "Azerbaycan" },
  { code: "KZ", name: "Kazakistan" },
  { code: "UZ", name: "Özbekistan" },
  { code: "GE", name: "Gürcistan" },
  { code: "AM", name: "Ermenistan" },
  { code: "TM", name: "Türkmenistan" },
  { code: "IQ", name: "Irak" },
  { code: "IR", name: "İran" },
  { code: "PK", name: "Pakistan" },
  { code: "ID", name: "Endonezya" },
  { code: "MY", name: "Malezya" },
  { code: "TH", name: "Tayland" },
  { code: "VN", name: "Vietnam" },
] as const;

export type CountryCode = typeof COUNTRIES[number]["code"];

export function flagEmoji(code: string): string {
  return code
    .toUpperCase()
    .split("")
    .map(c => String.fromCodePoint(0x1F1E6 + c.charCodeAt(0) - 65))
    .join("");
}
